# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI and Docker Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      platform:
        description: 'Docker platform (e.g., linux/amd64, linux/arm64)'
        default: 'linux/arm64'
      tag:
        description: 'Docker tag (e.g., v1, latest)'
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Build with Ant
        run: ant -noinput -buildfile build.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
            --platform ${{ github.event.inputs.platform || 'linux/arm64' }} \
            --tag jundog777/ci-cd:${{ github.event.inputs.tag || 'latest' }} .

      - name: Push Docker Image
        run: docker push jundog777/ci-cd:${{ github.event.inputs.tag || 'latest' }}
