# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: PROD
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '23'

    - name: Build with Ant
      run: ant -noinput -buildfile build.xml

    - name: Build and publish Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: jundog777/ci-cd
        tags: v1, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}        